package xoric.prism.data.modules;

public enum ErrorID
{
	COMMON,
	INVALID_LOGIN,
	ATTACHMENT_NOT_FOUND,
	FILE_NOT_FOUND,
	WRITE_ERROR,
	INVALID_INDEX,
	READ_ERROR,
	COMPILE_ERROR,
	PATH_NOT_FOUND,
	UNEXPECTED_LINE,
	CORRUPT_LINE,
	META_BLOCK_MISSING,
	META_LINE_MISSING,
	COMPRESSION_ERROR
}
